# routes.yml

prettyblocks_admin_index:
  path: /prettyblocks/admin
  methods: [ GET ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Admin\EditionController::indexAction

prettyblocks_zone_list:
  path: /prettyblocks/api/zones
  methods: [ GET ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\ZoneController:listZones

prettyblocks_zone_get:
  path: /prettyblocks/api/zones/{id}
  methods: [ GET ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\ZoneController:getZone

prettyblocks_zone_update:
  path: /prettyblocks/api/zones/{id}
  methods: [ PUT ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\ZoneController:updateZone

prettyblocks_media_upload:
  path: /prettyblocks/api/media/upload
  methods: [ POST ]
  defaults:
    _controller: PrestaSafe\PrettyBlocks\Controller\Api\MediaController:uploadMedia
